# Setup Script for DevSecOps Portfolio Project
# This script helps you set up the Azure infrastructure

Write-Host "================================" -ForegroundColor Cyan
Write-Host "DevSecOps Portfolio - Azure Setup" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# Check prerequisites
Write-Host "Checking prerequisites..." -ForegroundColor Yellow

# Check Azure CLI
try {
    $azVersion = az version --output json | ConvertFrom-Json
    Write-Host "✓ Azure CLI installed: $($azVersion.'azure-cli')" -ForegroundColor Green
} catch {
    Write-Host "✗ Azure CLI not found. Please install from: https://aka.ms/installazurecliwindows" -ForegroundColor Red
    exit 1
}

# Check Terraform
try {
    $tfVersion = terraform version -json | ConvertFrom-Json
    Write-Host "✓ Terraform installed: $($tfVersion.terraform_version)" -ForegroundColor Green
} catch {
    Write-Host "✗ Terraform not found. Please install from: https://www.terraform.io/downloads" -ForegroundColor Red
    exit 1
}

# Check kubectl
try {
    $kubectlVersion = kubectl version --client -o json | ConvertFrom-Json
    Write-Host "✓ kubectl installed: $($kubectlVersion.clientVersion.gitVersion)" -ForegroundColor Green
} catch {
    Write-Host "✗ kubectl not found. Please install from: https://kubernetes.io/docs/tasks/tools/" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "All prerequisites met!" -ForegroundColor Green
Write-Host ""

# Azure Login
Write-Host "Logging into Azure..." -ForegroundColor Yellow
az login

if ($LASTEXITCODE -ne 0) {
    Write-Host "✗ Azure login failed" -ForegroundColor Red
    exit 1
}

Write-Host "✓ Logged into Azure" -ForegroundColor Green
Write-Host ""

# Select subscription
Write-Host "Available subscriptions:" -ForegroundColor Yellow
az account list --output table

Write-Host ""
$subscriptionId = Read-Host "Enter subscription ID to use"

az account set --subscription $subscriptionId

if ($LASTEXITCODE -ne 0) {
    Write-Host "✗ Failed to set subscription" -ForegroundColor Red
    exit 1
}

Write-Host "✓ Subscription set" -ForegroundColor Green
Write-Host ""

# Get configuration
Write-Host "Configuration:" -ForegroundColor Yellow
$projectName = Read-Host "Project name (default: devsecops)"
if ([string]::IsNullOrWhiteSpace($projectName)) {
    $projectName = "devsecops"
}

$environment = Read-Host "Environment (dev/staging/prod, default: dev)"
if ([string]::IsNullOrWhiteSpace($environment)) {
    $environment = "dev"
}

$location = Read-Host "Azure region (default: eastus)"
if ([string]::IsNullOrWhiteSpace($location)) {
    $location = "eastus"
}

Write-Host ""
Write-Host "Summary:" -ForegroundColor Cyan
Write-Host "  Project Name: $projectName" -ForegroundColor White
Write-Host "  Environment: $environment" -ForegroundColor White
Write-Host "  Location: $location" -ForegroundColor White
Write-Host "  Subscription: $subscriptionId" -ForegroundColor White
Write-Host ""

$confirm = Read-Host "Proceed with setup? (yes/no)"
if ($confirm -ne "yes") {
    Write-Host "Setup cancelled" -ForegroundColor Yellow
    exit 0
}

# Create Service Principal for Terraform
Write-Host ""
Write-Host "Creating Service Principal for Terraform..." -ForegroundColor Yellow

$spName = "$projectName-$environment-terraform-sp"
$sp = az ad sp create-for-rbac --name $spName --role="Contributor" --scopes="/subscriptions/$subscriptionId" --output json | ConvertFrom-Json

if ($LASTEXITCODE -ne 0) {
    Write-Host "✗ Failed to create service principal" -ForegroundColor Red
    exit 1
}

Write-Host "✓ Service Principal created" -ForegroundColor Green
Write-Host ""

# Save credentials
Write-Host "Saving Terraform credentials..." -ForegroundColor Yellow

$tfVarsContent = @"
# Terraform Variables
# Generated by setup script on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

project_name = "$projectName"
environment  = "$environment"
location     = "$location"

# Azure credentials (use environment variables in production)
# Set these as environment variables instead:
# export ARM_CLIENT_ID="$($sp.appId)"
# export ARM_CLIENT_SECRET="$($sp.password)"
# export ARM_SUBSCRIPTION_ID="$subscriptionId"
# export ARM_TENANT_ID="$($sp.tenant)"
"@

$tfVarsContent | Out-File -FilePath "terraform\terraform.tfvars" -Encoding UTF8

Write-Host "✓ Terraform variables saved to terraform\terraform.tfvars" -ForegroundColor Green
Write-Host ""

# Display environment variables
Write-Host "Set these environment variables:" -ForegroundColor Cyan
Write-Host ""
Write-Host "`$env:ARM_CLIENT_ID = `"$($sp.appId)`"" -ForegroundColor Yellow
Write-Host "`$env:ARM_CLIENT_SECRET = `"$($sp.password)`"" -ForegroundColor Yellow
Write-Host "`$env:ARM_SUBSCRIPTION_ID = `"$subscriptionId`"" -ForegroundColor Yellow
Write-Host "`$env:ARM_TENANT_ID = `"$($sp.tenant)`"" -ForegroundColor Yellow
Write-Host ""

# Save to .env file (for reference, DO NOT commit)
$envContent = @"
# Azure Terraform Credentials
# DO NOT COMMIT THIS FILE
# Generated on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

ARM_CLIENT_ID=$($sp.appId)
ARM_CLIENT_SECRET=$($sp.password)
ARM_SUBSCRIPTION_ID=$subscriptionId
ARM_TENANT_ID=$($sp.tenant)
"@

$envContent | Out-File -FilePath ".env" -Encoding UTF8

Write-Host "✓ Credentials saved to .env file (DO NOT COMMIT)" -ForegroundColor Green
Write-Host ""

# Set environment variables for current session
$env:ARM_CLIENT_ID = $sp.appId
$env:ARM_CLIENT_SECRET = $sp.password
$env:ARM_SUBSCRIPTION_ID = $subscriptionId
$env:ARM_TENANT_ID = $sp.tenant

Write-Host "✓ Environment variables set for current session" -ForegroundColor Green
Write-Host ""

# Initialize Terraform
Write-Host "Initializing Terraform..." -ForegroundColor Yellow
Set-Location terraform
terraform init

if ($LASTEXITCODE -ne 0) {
    Write-Host "✗ Terraform init failed" -ForegroundColor Red
    Set-Location ..
    exit 1
}

Write-Host "✓ Terraform initialized" -ForegroundColor Green
Write-Host ""

# Terraform plan
Write-Host "Running Terraform plan..." -ForegroundColor Yellow
terraform plan -out=tfplan

if ($LASTEXITCODE -ne 0) {
    Write-Host "✗ Terraform plan failed" -ForegroundColor Red
    Set-Location ..
    exit 1
}

Write-Host "✓ Terraform plan completed" -ForegroundColor Green
Write-Host ""

Set-Location ..

# Summary
Write-Host "================================" -ForegroundColor Cyan
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Review the Terraform plan in terraform/tfplan" -ForegroundColor White
Write-Host "2. Apply the infrastructure:" -ForegroundColor White
Write-Host "   cd terraform" -ForegroundColor Cyan
Write-Host "   terraform apply tfplan" -ForegroundColor Cyan
Write-Host ""
Write-Host "3. Get AKS credentials:" -ForegroundColor White
Write-Host "   az aks get-credentials --resource-group $projectName-$environment-rg --name $projectName-$environment-aks" -ForegroundColor Cyan
Write-Host ""
Write-Host "4. Verify cluster access:" -ForegroundColor White
Write-Host "   kubectl get nodes" -ForegroundColor Cyan
Write-Host ""
Write-Host "5. Set up Jenkins (see docs/jenkins-setup.md)" -ForegroundColor White
Write-Host ""
Write-Host "⚠️  IMPORTANT: Keep your .env file secure and DO NOT commit it to git!" -ForegroundColor Red
Write-Host ""
